name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        # Filename for archive
        filename: Log-Converter-release.zip
        # Working directory before zipping
        directory: LogConverter/bin/Release/
        # List of excluded files/directories
        exclusions: '*.pdb *.dev'
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Log-Converter
        # A file, directory or wildcard pattern that describes what to upload
        path: Log-Converter-release.zip
